### ISSUE TITLE
Tag a new version for npmjs.

### ISSUE THREAD

**Issue by pwhelan** [pwhelan/node-X11-desktop-entry#6]
Any chance of updating or adding a new version to npmjs?

**Comment by opatry** [comment]
For sure, I can do if you require it.
I sent you an email this week about this project, can you check your mail box? (the one you mentioned in your github profile)
It is a little bit related to your question.

**Comment by pwhelan** [comment]
I have now published the package as node-x11-desktop-entry on npm and tagged the new version.
